defaults:
- common
- ../materials/dough@material

geom:
  type: mesh
  file: null  # This will be populated programmatically with the Objaverse object file
  scale: 1.0  # Adjust as needed
  pos: (0.0, 0.0, 0.0)  # Adjust as needed
  euler: (0.0, 0.0, 0.0)  # Adjust as needed

  # preprocessing
  offset_pos: (0.0, 0.0, 0.0)
  offset_euler: (0.0, 0.0, 0.0)

material:
  filling: jittered

objaverse_id: null  # This will be populated programmatically

enabled: true
