# set pre-grasp pose and opening, move to grasp pose, close gripper

defaults:
- common
- push

wait: 0
type: grasp
from_offset:
- 0.0
- 0.0
- 0.0
to_pos:
- 0.0
- 0.0
- 0.0
to_quat:
- 0.96592583
- 0.0
- 0.0
- 0.25881905
init_d: 0.5
close_d: 0.005