# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Oct 17 16:13:06 2024
# ------------------------------------------------

package:
  name: micromamba
  version: 2.0.2
source:
  - folder: mamba
    sha256: 52a9ffe51d7da271cd4c5c200346f757531d9b41ef6a9ce9edc86891ce5520bd
    url: https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-2.0.2.tar.gz
build:
  ignore_run_exports_from:
    - fmt
    - gcc_linux-64 13.*
    - gxx_linux-64 13.*
    - libarchive-minimal-static
    - libcurl
    - libsolv
    - openssl
    - spdlog
    - zlib
  number: '1'
  string: '1'
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_1
    - binutils_linux-64 2.43 h4852527_1
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.32.3 h4bc722e_0
    - ca-certificates 2024.8.30 hbcca054_0
    - cmake 3.30.5 hf9cb763_0
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_4
    - gxx_impl_linux-64 13.3.0 hdbfa832_1
    - gxx_linux-64 13.3.0 h6834431_4
    - kernel-headers_linux-64 3.10.0 he073ed8_17
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.43 h712a8e2_1
    - libcurl 8.10.1 hbbe4b11_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.3 h5888daf_0
    - libgcc 14.2.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libssh2 1.11.0 h0841786_0
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libstdcxx-devel_linux-64 13.3.0 h84ea5a7_101
    - libstdcxx-ng 14.2.0 h4852527_1
    - libuv 1.49.1 hb9d3cd8_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - ninja 1.12.1 h297d8ca_0
    - openssl 3.3.2 hb9d3cd8_0
    - rhash 1.4.5 hb9d3cd8_0
    - sysroot_linux-64 2.17 h4a8ded7_17
    - tzdata 2024b hc8b5060_0
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.32.3 h4bc722e_0
    - c-ares-static 1.32.3 h4bc722e_0
    - ca-certificates 2024.8.30 hbcca054_0
    - cli11 2.4.1 h59595ed_0
    - cpp-expected 1.1.0 hf52228f_0
    - fmt 11.0.2 h434a139_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - krb5-static 1.21.3 h659f571_0
    - libarchive-minimal-static 3.7.4 h707859c_0
    - libcurl 8.10.1 hbbe4b11_0
    - libcurl-static 8.10.1 hbbe4b11_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libev-static 4.33 hd590300_2
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnghttp2 1.58.0 h47da74e_1
    - libnghttp2-static 1.58.0 h6bbaf85_1
    - libopenssl-static 3.3.2 hb9d3cd8_0
    - libsolv 0.7.30 h3509ff9_0
    - libsolv-static 0.7.30 h3509ff9_0
    - libssh2 1.11.0 h0841786_0
    - libssh2-static 1.11.0 h0841786_0
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libstdcxx-ng 14.2.0 h4852527_1
    - libzlib 1.3.1 hb9d3cd8_2
    - lz4-c-static 1.9.4 ha770c72_0
    - ncurses 6.5 he02047a_1
    - nlohmann_json 3.11.3 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - reproc-cpp-static 14.2.4.post0 h59595ed_1
    - reproc-static 14.2.4.post0 hd590300_1
    - simdjson 3.10.1 h84d6215_0
    - simdjson-static 3.10.1 h1a2810e_0
    - spdlog 1.14.1 hed91bc2_1
    - xz 5.2.6 h166bdaf_0
    - xz-static 5.2.6 h166bdaf_0
    - yaml-cpp-static 0.8.0 h59595ed_0
    - zlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.6 ha6fb4c9_0
    - zstd-static 1.5.6 hac33072_0
  run:
    - __glibc >=2.17,<3.0.a0
test:
  commands:
    - test -f "${PREFIX}/bin/micromamba"
    - test ! -f "${PREFIX}/etc/profile.d/mamba.sh"
    - micromamba --help
    - export MAMBA_ROOT_PREFIX="$(mktemp -d)"
    - micromamba create -n test --override-channels -c conda-forge --yes python=3.9
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" --version'
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" -c "import os"'
about:
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  license_file:
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZLIB_LICENSE.txt
    - ZSTD_LICENSE.txt
    - mamba/LICENSE
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241017.3.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - jjerphan
    - mariusvniekerk
    - pavelzw
    - wolfv
  remote_url: https://github.com/conda-forge/micromamba-feedstock
  sha: 6abfa12cb5b6c6a8b01f462234128921945bc853
