defaults:
- common
- objects/ground@entities.ground
# - objects/supertoroid@entities.donut
# - objects/cube@entities.left
# - objects/roll@entities.right
- ee/gripper@ee
# - actions/grasp@actions.grasp
- actions/random_grasp@actions.random_grasp
- objects/objaverse@entities.objaverse_object
- _self_

scene_id: smaller_voxels/scene_9bc4b401fb
num_grasps: 5  # Number of random grasps to attempt

render: true
log:
  base_dir:  data/
check:
  horizon: ${eval:'${log.n_iter} * 10'}  # -1 deactivates topology check
